### ISSUE TITLE
BAF and LRR

### ISSUE THREAD

**Issue by freeseek** [Illumina/GTCtoVCF#14]
With GenomeStudio it is possible to output information such as BAF and LRR from the GTC files. I don't understand how it is possible to do the same using GTCtoVCF. It seems like it would be something very easy to add.

**Comment by freeseek** [comment]
I used the following conventions:
```
FORMAT/IGC      Number:1  Type:Float    ..  Illumina GenCall Confidence Score
FORMAT/BAF      Number:1  Type:Float    ..  B Allele Frequency
FORMAT/LRR      Number:1  Type:Float    ..  Log R Ratio
FORMAT/NORMX    Number:1  Type:Float    ..  Normalized X intensity
FORMAT/NORMY    Number:1  Type:Float    ..  Normalized Y intensity
FORMAT/R        Number:1  Type:Float    ..  Normalized R value
FORMAT/THETA    Number:1  Type:Float    ..  Normalized Theta value
FORMAT/X        Number:1  Type:Integer  ..  Raw X intensity
FORMAT/Y        Number:1  Type:Integer  ..  Raw Y intensity
```
I did not understand though that only GTC files generated with AutoConvert 2.0 include the BAF and LRR information and that otherwise this information requires both the BPM and EGT files to be recovered if not included in the GTC file to begin with.

I think when multiple entries are present treating as missing data is a good approach.

**Comment by jjzieve** [comment]
See latest version (1.2.0) it should support BAF and LRR output
