### ISSUE TITLE
Reference allele is not queried for locus

### ISSUE THREAD

**Issue by stephenturner** [Illumina/GTCtoVCF#2]
I'm seeing 52 lines in the log that the reference allele isn't queried for a particular locus for the omni array I'm running (which includes some custom content) What causes this, and what should be done about it? 

Here are a couple of examples. Looks like the reference allele is one thing, but the possible alleles (presumably from the manifest) do not include the reference allele. Is this an error in the manifest?

```
7       16831874        rs28945081      C       T,G     .       PASS    .       GT:GQ   2/2:0.49126184
15      20740293        rs373904595     T       G,C     .       PASS    .       GT:GQ   2/2:0.32350013
```

**Comment by KelleyRyanM** [comment]
Hi Stephen,
 Most commonly there is an issue with the mapping information provided in the manifest. Although in some cases, the manifest is accurate and the assays for that location are not designed to query the reference allele. In the common case, the correction would be to either update or remove the entry from the manifest. For your specific semi-custom manifest, I've sent a follow-up e-mail to the address given on your webpage to go into more detail.
  -Ryan
