### ISSUE TITLE
vcf.parser error

### ISSUE THREAD

**Issue by biopelayo** [Illumina/GTCtoVCF#25]
Hi Ryan:
i'm a biologist learning bioinformatics. 
When using your facility GTCtoVCF i have this error. 
Could you please help me? I went step by step througt the readme file
I really appreciate your advice.
Thank you in advance

Pelayo

Traceback (most recent call last):
  File "./gtc_to_vcf.py", line 9, in <module>
    from vcf.parser import Writer, Reader
ImportError: No module named vcf.parser

**Comment by KelleyRyanM** [comment]
Hi Pelayo,
  Have you installed the pyvcf module in your python installation? Do you know which version this is? The README.md file describes how you would do this if you are using anaconda to manage your python installation.
  -Ryan

**Comment by biopelayo** [comment]
Hi Ryan.

Yes, some of the python modules did not where in the path... keep on learning!!
Issue solved, i have the .vcf derived from the manifest at least!!
Thank you so much.

Pela


By the way, i hace just started to work as a junior bioinformatician for ICM Genetic Lab at Lugo, here in Spain. My lab has bought iScan tecnology and GSA v2 chip to your company. 

In fact, next Friday, the 26th we will receive a colleague of yours from Illumina for a training webinar on the GenomeStudio software that illumina has offered for our support.
As you know, bioinformatics are more Unix friends than windows and that's why I'm noting the manifest and also analyzing the GenomeStudio output for genotyping. This process is currently automated and returns 4 files as output:

sample data
sample table
snp table
full data table


Having the vcf generated from the manifest that contains the possible alleles that the chip can map, I only need the genotype of the sample for that position and so I will know my letters for that position, right?
e.g. chr 1       pos 8728378        rs ******       REF T          ALT G             GTYPE AB

My snps are TA and GC for that locus for that chromosome, right?

I downloaded all the technical product and support files for our GSA 24  v2 from the illumina website to start working.

Can you give me some advice that you think should be taken into account with your technology?

Sorry if my message is not appropriate. If so, you could contact me with an illumina's bioinformatician who could give me bioinformatic support (software, workflows, pipelines, programs like GTCtoVCF !!!,) to handle, manage, store and analyze data from GSA24 v2)?

Again i really appreciate to time and atention.

Kindly,



Pelayo
