### ISSUE TITLE
Contig header and Chrom record order do not match reference order

### ISSUE THREAD

**Issue by brmyers** [Illumina/GTCtoVCF#28]
Something I'm altering with post-processing, but it'd be nice if the contig order matched the reference given. In my example, the reference is 1-22,X,Y,MT and the program writes contig headers and records as 1-22,MT, X,Y.

If the reference order was maintained I think that would obviate concerns about "human specific" sorting in code.

Thanks!

**Comment by KelleyRyanM** [comment]
Candidate implementation of this is available in branch https://github.com/Illumina/GTCtoVCF/tree/python3_compatibility, currently open pull request at https://github.com/Illumina/GTCtoVCF/pull/30.
