### ISSUE TITLE
GQ type is "String" instead of "Float"

### ISSUE THREAD

**Issue by kmhernan** [Illumina/GTCtoVCF#51]
I see that in this line https://github.com/Illumina/GTCtoVCF/blob/1a9709baa7116eea56e09dd185bd4358a165f34d/GencallFormat.py#L33 the `GQ` type is set to `String` but isn't it a `Float`? This has caused segfaults in some other downstream tools. When I change `String` to `Float` it's fine.

**Comment by jjzieve** [comment]
This was changed to an Integer in PR #53
