### ISSUE TITLE
download_reference.sh is outdated

### ISSUE THREAD

**Issue by moranr7** [Illumina/GTCtoVCF#54]
Hey, 

The $remote FTP site seems to have changed for build 38 to :
ftp://ftp.ncbi.nlm.nih.gov/genomes/Homo_sapiens/Assembled_chromosomes/GCF_000001405.39_GRCh38.p13_assembly_structure/Primary_Assembly/assembled_chromosomes/FASTA/

**Comment by tedyun** [comment]
I think it should be this one (the above link is also down):

`ftp://ftp.ncbi.nlm.nih.gov/genomes/Homo_sapiens/current/GCF_000001405.39_GRCh38.p13/GCF_000001405.39_GRCh38.p13_assembly_structure/Primary_Assembly/assembled_chromosomes/FASTA/`

**Comment by tedyun** [comment]
Or this: `ftp://ftp.ncbi.nlm.nih.gov/genomes/Homo_sapiens/ARCHIVE/ANNOTATION_RELEASE.109/Assembled_chromosomes/seq/`

**Comment by jjzieve** [comment]
Thanks for the info @tedyun! Should be fixed with PR #39
