### ISSUE TITLE
Unable to run download_reference.sh on Mac

### ISSUE THREAD

**Issue by biying-orig3n** [Illumina/GTCtoVCF#55]
I tried to build suitable whole genome FASTA files can be built with the download_reference.sh script on macOS Mojave:
./download_reference.sh output-37.fa 37

 I got this error:
readlink: illegal option -- f
usage: readlink [-n] [file ...]
usage: dirname path

Does anyone know how to fix it? Thanks in advance!

**Comment by jjzieve** [comment]
Hi, can you try this PR branch? https://github.com/Illumina/GTCtoVCF/pull/39

**Comment by jjzieve** [comment]
Should be fixed with PR #39
