### ISSUE TITLE
Error using manifest in CSV format

### ISSUE THREAD

**Issue by smparsons96** [Illumina/GTCtoVCF#6]
A user is attempting to run the conversion using the CSV version of the manifest file in order to generate indel records in the vcf. It results in an error (see attached) suggesting the same version must be used as was used during generation of gtc calls.  

![error](https://user-images.githubusercontent.com/36311227/36047742-efb4bb76-0daa-11e8-8b3b-0d4f6958a74e.png)

**Comment by YongFugaLi** [comment]
Hi @smparsons96 , 
If the user knows for sure that "GSA-24v1-0_A6.csv" is the file used to generate "GSA-24v1-0_A6-hg37.bpm", then renaming "GSA-24v1-0_A6.csv" to "GSA-24v1-0_A6-hg37.csv" should solve the problem.

**Comment by smparsons96** [comment]
Thanks, that was my suspicion as well.
