### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by varuna-sd** [Illumina/GTCtoVCF#60]
There is about 9 months difference between the latest commit of develop and master branches. When do you plan to do a new release to add latest changes to the master (and new version tag)?

**Comment by jjzieve** [comment]
https://github.com/Illumina/GTCtoVCF/pull/61

**Comment by jjzieve** [comment]
New release 1.2.1 tagged on master: https://github.com/Illumina/GTCtoVCF/tree/1.2.1
