### ISSUE TITLE
Python3 Question

### ISSUE THREAD

**Issue by tbrunetti** [Illumina/GTCtoVCF#65]
The README on your github states to use python 2.7, which will reach end-of-life the end of this year.  Is this compatible with python3 yet?  If not, I can update the code myself, but if it is, it saves me a lot of time. 

Thanks

**Comment by jjzieve** [comment]
It should be compatible with python3. It was developed with python2.7 which is where the README reference comes from.  Are there any specific issues with python3?

**Comment by tbrunetti** [comment]
Ah I see, great thank you!

**Comment by jjzieve** [comment]
Update on this. See https://github.com/Illumina/GTCtoVCF/issues/71
