### ISSUE TITLE
Bus error when converting GTC to VCF

### ISSUE THREAD

**Issue by khzhu** [Illumina/GTCtoVCF#67]
Hi Illumina team, 
we got an "Bus error" when trying to convert a GTC file to VCF.  The GTC file was generated from the Infinium LCG Assay idat files using iaap-cli gencall tool on linux.
1. error message
`2020-10-21 12:32:35,934 - GTC converter - WARNING - Reference allele is not queried for locus: rs876659253_mnv
2020-10-21 12:32:35,941 - GTC converter - WARNING - Reference allele is not queried for locus: ilmnseq_rs878853738_mnv
2020-10-21 12:32:35,957 - GTC converter - WARNING - Reference allele is not queried for locus: rs886040595_mnv
Bus error`
2. command used
`~/molecpathlab/bin/GTCtoVCF/gtc_to_vcf.py --gtc-paths /gpfs/data/molecpathlab/development/Infinium_LCG/test  --manifest-file /gpfs/data/molecpathlab/data/Infinium/GDA-8v1-0_A1.csv  --genome-fasta-file /gpfs/data/molecpathlab/data/Infinium/genome.fa  --output-vcf-path /gpfs/data/molecpathlab/development/Infinium_LCG/test --log-file /gpfs/data/molecpathlab/development/Infinium_LCG/test/Infinium_LCG_test.log --skip-indels --disable-genome-cache`

**Comment by jjzieve** [comment]
Hi @khzhu, this seems like a lower-level python error I have not encountered before.
Can you post more details on your environment (python version, exact OS, memory, CPU)?
Also can you try not providing a `--log-file`?

**Comment by khzhu** [comment]
Hi @jjzieve , 
not sure if the log file helps but it's attached for your reference.
[Infinium_LCG_test.log](https://github.com/Illumina/GTCtoVCF/files/5426094/Infinium_LCG_test.log)
below is our environment:
1. python : Python 3.6.5
2. OS: Red Hat Enterprise Linux 7.4
3. Cores: 39 
4. RAM: 395GB

**Comment by jjzieve** [comment]
ok seems like its not a hardware issue then, you have more than enough resources.
Can you send us one of you GTCs so we can try to reproduce?

**Comment by khzhu** [comment]
@jjzieve , I've already sent the file to the Illumina technical support. It is really patient data and cannot share it on Github.

**Comment by jjzieve** [comment]
@khzhu I wasn't able to reproduce the issue. techsupport can point you to my log and the created VCF file.
Is this reproducible on another machine you have access to (or after a reboot)? Are there more logs if you run `python -v` (i.e. with tracing).
This SO post suggests a `Bus error` could be an actual hardware problem after all? It's difficult to determine the exact cause since I can't reproduce on my end.

**Comment by khzhu** [comment]
@jjzieve, were you running GTCtoVCF on Windows or Linux?

**Comment by khzhu** [comment]
@jjzieve , I got the issue resolved. The error was caused by missing PyVCF and pysam two modules. After pip install dependencies, I was able to convert my GTCs to VCFs.
It will be helpful to have a requirements.txt included in GTCtoVCF git branch.

**Comment by jjzieve** [comment]
@khzhu that's good to hear. I realize https://github.com/Illumina/GTCtoVCF#requirements is not as straightforward as a requirements.txt. I referenced this issue in a previous semi related issue (#17) to track creating a requirements.txt.
