### ISSUE TITLE
Script reports that reference has missing chromosome 6

### ISSUE THREAD

**Issue by YourLogoHere** [Illumina/GTCtoVCF#8]
Is there a known cause for why the script will report the following error upon execution? 

"2018-03-01 16:51:29,607 - GTC converter - ERROR - FASTA reference is missing entry for chromosome 6"

This seems to only be a problem with the GrCh38 reference; it seems to work fine with build 37.

**Comment by YourLogoHere** [comment]
I forgot to add that this error seems to be inconsistent with regard to which chromosome it says it's missing --- running it multiple times has given reports of the reference missing chr 3, 12, etc.

**Comment by KelleyRyanM** [comment]
In your reference file, is chromosome 6 named as "6" or "chr6"?

**Comment by YourLogoHere** [comment]
Ah; that was it --- was using hg38 rather than GrCh38. Just as a heads up though, the FTP link provided in the README has the contigs with the "chr" prefix, even though it's ostensibly GrCh38 --- that was what ended up confusing me; I didn't check the reference beforehand.

**Comment by KelleyRyanM** [comment]
Thank you for noting this issue. The documentation has been updated to reference a newly added script that can be used to build the appropriate reference sequence.
